/* Basisvoedingsmiddelen voor "Product zoeken".
 * Per item: [naam, eiwit g per 100 g, kcal per 100 g, extra zoekwoorden]
 * Gemiddelde, indicatieve waarden (geen officiële NEVO-cijfers). Merkproducten
 * komen uit Open Food Facts; deze lijst dekt onverpakte basisproducten. */
window.GENERIC_FOODS = [
  // Eieren
  ['Ei, gekookt', 12.6, 140, 'kippenei hardgekookt zachtgekookt'],
  ['Ei, rauw', 12.6, 140, 'kippenei'],
  ['Ei, gebakken', 13.6, 196, 'spiegelei kippenei'],
  ['Roerei', 11, 170, 'ei'],
  ['Eiwit (van ei)', 10.9, 48, 'eiwitten'],
  ['Eidooier', 16, 322, 'ei dooier'],

  // Zuivel
  ['Melk, halfvol', 3.5, 46, 'halfvolle melk'],
  ['Melk, vol', 3.4, 62, 'volle melk'],
  ['Melk, mager', 3.6, 35, 'magere melk'],
  ['Melk, lactosevrij halfvol', 3.5, 46, 'lactosevrije melk'],
  ['Karnemelk', 3.3, 33, ''],
  ['Koffiemelk, halfvol', 7.7, 106, 'koffie melk'],
  ['Koffiemelk, vol', 7.6, 140, 'koffie melk'],
  ['Yoghurt, halfvol', 4, 48, 'halfvolle yoghurt'],
  ['Yoghurt, vol', 3.9, 63, 'volle yoghurt'],
  ['Yoghurt, Griekse stijl', 5.5, 125, 'griekse yoghurt'],
  ['Kwark, mager', 8.5, 57, 'magere kwark'],
  ['Skyr', 11, 63, 'kwark'],
  ['Hüttenkäse', 11, 100, 'cottage cheese huttenkase'],
  ['Vla, vanille', 3.1, 101, 'vanillevla'],
  ['Kaas, jong 48+', 23, 355, 'goudse kaas jonge'],
  ['Kaas, belegen 48+', 25, 370, 'goudse kaas belegen'],
  ['Kaas, oud 48+', 29, 390, 'goudse kaas oude'],
  ['Kaas, 30+', 30, 265, 'magere kaas'],
  ['Mozzarella', 18, 240, 'kaas'],
  ['Feta', 16, 265, 'kaas'],
  ['Brie', 20, 335, 'kaas'],
  ['Parmezaanse kaas', 34, 400, 'parmezaan kaas'],
  ['Roomkaas', 6, 230, 'kaas smeerkaas'],
  ['Boter', 0.6, 740, 'roomboter'],
  ['Halvarine', 0.1, 350, 'light margarine becel'],
  ['Margarine', 0.1, 640, 'kuipje'],
  ['Slagroom', 2.1, 335, 'room'],
  ['Sojadrink, ongezoet', 3.3, 35, 'sojamelk'],
  ['Havermelk', 1, 45, 'haverdrink'],
  ['Amandeldrink, ongezoet', 0.5, 14, 'amandelmelk'],

  // Brood, graan, aardappel
  ['Brood, volkoren', 10, 230, 'volkorenbrood boterham snee'],
  ['Brood, meergranen', 10.5, 250, 'meergranenbrood vikorn boterham snee'],
  ['Brood, bruin', 9.5, 235, 'bruinbrood boterham snee'],
  ['Brood, wit', 8.5, 250, 'witbrood boterham snee'],
  ['Brood, spelt', 10, 240, 'speltbrood boterham'],
  ['Brood, zuurdesem', 9, 245, 'zuurdesembrood desem'],
  ['Brood, glutenvrij', 3, 240, 'glutenvrij brood'],
  ['Krentenbol', 8, 280, 'brood'],
  ['Croissant', 8, 410, ''],
  ['Beschuit', 10, 400, ''],
  ['Knäckebröd', 10, 360, 'knackebrod cracker'],
  ['Rijstwafel', 8, 385, 'rijstwafels'],
  ['Cracker', 10, 440, 'crackers'],
  ['Tortilla wrap', 8, 300, 'wrap'],
  ['Pannenkoek', 6, 200, 'pannenkoeken'],
  ['Havermout', 13, 370, 'haver oats'],
  ['Muesli', 10, 360, ''],
  ['Cornflakes', 7, 375, ''],
  ['Rijst, wit, gekookt', 2.6, 125, 'witte rijst'],
  ['Rijst, zilvervlies, gekookt', 3, 130, 'bruine rijst'],
  ['Rijst, ongekookt', 7, 355, 'rijst droog'],
  ['Pasta, gekookt', 5.5, 145, 'spaghetti macaroni penne'],
  ['Pasta, volkoren, gekookt', 5.5, 130, 'volkorenpasta spaghetti'],
  ['Pasta, ongekookt', 12.5, 355, 'spaghetti macaroni droog'],
  ['Mie/noedels, gekookt', 4.5, 138, 'mie noedels bami'],
  ['Couscous, gekookt', 3.8, 112, ''],
  ['Quinoa, gekookt', 4.4, 120, ''],
  ['Aardappelen, gekookt', 1.9, 75, 'aardappel'],
  ['Aardappelpuree', 2, 95, 'puree aardappel'],
  ['Friet', 3.3, 260, 'patat frites'],
  ['Zoete aardappel, gekookt', 1.6, 85, 'bataat'],

  // Vlees
  ['Kipfilet, gebakken', 30, 155, 'kip kippenborst'],
  ['Kipfilet, rauw', 23, 110, 'kip kippenborst'],
  ['Kippendij, gebakken', 25, 190, 'kip kipdij'],
  ['Kalkoenfilet, gebakken', 29, 150, 'kalkoen'],
  ['Rundergehakt, gebakken', 26, 245, 'gehakt rund'],
  ['Gehakt half-om-half, gebakken', 24, 270, 'gehakt'],
  ['Biefstuk, gebakken', 29, 165, 'rund steak'],
  ['Varkenshaas, gebakken', 28, 150, 'varken'],
  ['Rookworst', 13, 295, 'worst'],
  ['Kipfilet (vleeswaren)', 21, 100, 'beleg kip'],
  ['Ham (vleeswaren)', 19, 110, 'beleg achterham'],
  ['Rookvlees', 26, 120, 'beleg'],
  ['Salami', 22, 400, 'beleg worst'],

  // Vis
  ['Zalm, gebakken', 24, 205, 'vis'],
  ['Zalm, gerookt', 21, 175, 'vis'],
  ['Tonijn in water, uitgelekt', 26, 110, 'vis blik'],
  ['Tonijn in olie, uitgelekt', 25, 195, 'vis blik'],
  ['Kabeljauw, gekookt', 21, 95, 'vis'],
  ['Garnalen, gekookt', 19, 95, 'vis'],
  ['Makreel, gerookt', 19, 300, 'vis'],
  ['Haring', 16, 220, 'vis maatjes'],
  ['Sardines in olie', 24, 210, 'vis blik'],

  // Vegetarisch, peulvruchten, noten
  ['Tofu', 13, 125, 'vegetarisch'],
  ['Tempeh', 19, 195, 'vegetarisch'],
  ['Linzen, gekookt', 9, 115, 'peulvruchten'],
  ['Kikkererwten, gekookt', 7.5, 125, 'peulvruchten blik'],
  ['Bruine bonen, gekookt', 7.5, 105, 'peulvruchten blik'],
  ['Kidneybonen, gekookt', 7, 100, 'peulvruchten blik'],
  ['Edamame', 11, 120, 'sojabonen'],
  ['Hummus', 7, 280, ''],
  ['Pindakaas', 25, 620, ''],
  ['Pinda\'s', 26, 590, 'pinda noten'],
  ['Amandelen', 21, 610, 'noten'],
  ['Walnoten', 15, 690, 'noten'],
  ['Cashewnoten', 18, 580, 'noten'],
  ['Zonnebloempitten', 21, 590, 'pitten zaden'],
  ['Chiazaad', 17, 490, 'zaden'],

  // Groente
  ['Broccoli, gekookt', 3, 33, 'groente'],
  ['Bloemkool, gekookt', 2, 25, 'groente'],
  ['Sperziebonen, gekookt', 2, 30, 'groente boontjes'],
  ['Spinazie, gekookt', 3, 24, 'groente'],
  ['Boerenkool, gekookt', 2.8, 34, 'groente'],
  ['Doperwten, gekookt', 5.5, 75, 'erwten groente'],
  ['Wortel', 0.7, 36, 'wortelen groente'],
  ['Komkommer', 0.6, 12, 'groente'],
  ['Tomaat', 0.9, 20, 'tomaten groente'],
  ['Paprika', 1, 30, 'groente'],
  ['Sla', 1, 14, 'ijsbergsla groente'],
  ['Courgette', 1.3, 18, 'groente'],
  ['Aubergine', 1, 22, 'groente'],
  ['Champignons', 3, 22, 'paddenstoelen groente'],
  ['Ui', 1.2, 40, 'uien groente'],
  ['Prei', 1.5, 30, 'groente'],
  ['Knoflook', 6.4, 145, ''],
  ['Pompoen', 1, 26, 'groente'],
  ['Rode biet, gekookt', 1.7, 44, 'bieten groente'],
  ['Asperges, gekookt', 2, 20, 'groente'],
  ['Maïs (blik)', 2.8, 85, 'mais groente'],
  ['Avocado', 2, 200, ''],
  ['Olijven', 1, 145, ''],

  // Fruit
  ['Banaan', 1.2, 90, 'fruit'],
  ['Appel', 0.3, 53, 'fruit'],
  ['Peer', 0.4, 55, 'fruit'],
  ['Sinaasappel', 0.9, 45, 'fruit'],
  ['Mandarijn', 0.8, 50, 'fruit'],
  ['Aardbeien', 0.7, 33, 'fruit'],
  ['Blauwe bessen', 0.7, 57, 'fruit bosbessen'],
  ['Frambozen', 1.2, 52, 'fruit'],
  ['Kiwi', 1.1, 60, 'fruit'],
  ['Druiven', 0.7, 70, 'fruit'],
  ['Ananas', 0.5, 50, 'fruit'],
  ['Mango', 0.8, 60, 'fruit'],
  ['Meloen', 0.8, 34, 'fruit'],
  ['Watermeloen', 0.6, 30, 'fruit'],
  ['Rozijnen', 3, 300, 'fruit gedroogd'],
  ['Dadels, gedroogd', 2.5, 280, 'fruit'],

  // Dranken
  ['Koffie, zwart', 0.1, 1, 'koffie'],
  ['Thee, zonder suiker', 0, 1, 'thee'],
  ['Sinaasappelsap', 0.7, 44, 'jus d\'orange sap'],
  ['Appelsap', 0.1, 45, 'sap'],
  ['Cola', 0, 42, 'frisdrank'],
  ['Cola zero / light', 0, 0, 'frisdrank'],
  ['Bier (pils)', 0.4, 42, 'alcohol'],
  ['Wijn, rood', 0.1, 70, 'alcohol'],
  ['Wijn, wit', 0.1, 70, 'alcohol'],
  ['Chocolademelk', 3.5, 75, 'chocomel'],
  ['Wheyproteïne (poeder)', 75, 390, 'eiwitshake proteine whey eiwitpoeder'],

  // Beleg, tussendoor, overig
  ['Hagelslag, puur', 5.5, 480, 'beleg'],
  ['Chocoladepasta', 5, 540, 'beleg'],
  ['Jam', 0.3, 250, 'beleg'],
  ['Honing', 0.3, 320, 'beleg'],
  ['Suiker', 0, 400, 'suikerklontje'],
  ['Olijfolie', 0, 900, 'olie'],
  ['Mayonaise', 1.2, 740, 'mayo'],
  ['Ketchup', 1.2, 110, ''],
  ['Chocolade, puur', 7, 550, ''],
  ['Chocolade, melk', 7, 540, ''],
  ['Chips, naturel', 6, 540, ''],
  ['Biscuit', 7, 440, 'koekje'],
  ['Ontbijtkoek', 4, 320, 'peperkoek']
];

/* Portie-eenheden per basisproduct: [label, gram per eenheid].
 * "gram" is altijd beschikbaar en hoeft hier niet te staan. Indicatieve,
 * gangbare Nederlandse portiegroottes. */
(function () {
  const EL = ['eetlepel', 15], TL = ['theelepel', 5], GLAS = ['glas', 200], BEKER = ['beker', 250],
    KOPJE = ['kopje', 125], SCHAAL = ['schaaltje', 150], OPSCHEP = ['opscheplepel', 50],
    HAND = ['handje', 25], PLAK_KAAS = ['plak', 20], PLAK_VLEES = ['plak', 15];
  window.GENERIC_PORTIONS = {
    'Ei, gekookt': [['stuk (middel)', 55], ['stuk (groot)', 65]],
    'Ei, rauw': [['stuk (middel)', 55], ['stuk (groot)', 65]],
    'Ei, gebakken': [['stuk', 50]],
    'Roerei': [['portie (2 eieren)', 120], EL],
    'Eiwit (van ei)': [['eiwit van 1 ei', 33]],
    'Eidooier': [['dooier van 1 ei', 17]],

    'Melk, halfvol': [GLAS, BEKER, KOPJE, ['scheutje', 15]],
    'Melk, vol': [GLAS, BEKER, KOPJE, ['scheutje', 15]],
    'Melk, mager': [GLAS, BEKER, KOPJE, ['scheutje', 15]],
    'Melk, lactosevrij halfvol': [GLAS, BEKER, KOPJE, ['scheutje', 15]],
    'Karnemelk': [GLAS, BEKER],
    'Koffiemelk, halfvol': [['cupje / scheutje', 7], EL],
    'Koffiemelk, vol': [['cupje / scheutje', 7], EL],
    'Yoghurt, halfvol': [SCHAAL, EL],
    'Yoghurt, vol': [SCHAAL, EL],
    'Yoghurt, Griekse stijl': [SCHAAL, EL],
    'Kwark, mager': [SCHAAL, EL],
    'Skyr': [SCHAAL, ['bakje', 150], EL],
    'Hüttenkäse': [['bakje', 200], EL],
    'Vla, vanille': [SCHAAL, EL],
    'Kaas, jong 48+': [PLAK_KAAS, ['blokje', 10]],
    'Kaas, belegen 48+': [PLAK_KAAS, ['blokje', 10]],
    'Kaas, oud 48+': [PLAK_KAAS, ['blokje', 10]],
    'Kaas, 30+': [PLAK_KAAS, ['blokje', 10]],
    'Mozzarella': [['bol', 125], ['plak', 20]],
    'Feta': [['blokje', 10], EL],
    'Brie': [['punt', 30], ['plak', 20]],
    'Parmezaanse kaas': [EL, ['eetlepel geraspt', 7]],
    'Roomkaas': [['voor 1 snee', 15], EL],
    'Boter': [['voor 1 snee', 6], EL, TL, ['klontje', 10]],
    'Halvarine': [['voor 1 snee', 6], EL, TL],
    'Margarine': [['voor 1 snee', 6], EL, TL],
    'Slagroom': [EL, ['toef', 20]],
    'Sojadrink, ongezoet': [GLAS, BEKER],
    'Havermelk': [GLAS, BEKER],
    'Amandeldrink, ongezoet': [GLAS, BEKER],

    'Brood, volkoren': [['snee', 35]],
    'Brood, meergranen': [['snee', 35]],
    'Brood, bruin': [['snee', 35]],
    'Brood, wit': [['snee', 30]],
    'Brood, spelt': [['snee', 35]],
    'Brood, zuurdesem': [['snee', 40]],
    'Brood, glutenvrij': [['snee', 30]],
    'Krentenbol': [['stuk', 60]],
    'Croissant': [['stuk', 45]],
    'Beschuit': [['stuk', 10]],
    'Knäckebröd': [['stuk', 12]],
    'Rijstwafel': [['stuk', 8]],
    'Cracker': [['stuk', 8]],
    'Tortilla wrap': [['stuk', 60]],
    'Pannenkoek': [['stuk', 90]],
    'Havermout': [['portie (droog)', 40], EL],
    'Muesli': [['portie', 45], EL],
    'Cornflakes': [['portie', 30], EL],
    'Rijst, wit, gekookt': [OPSCHEP, ['portie', 200]],
    'Rijst, zilvervlies, gekookt': [OPSCHEP, ['portie', 200]],
    'Rijst, ongekookt': [['portie', 75]],
    'Pasta, gekookt': [OPSCHEP, ['portie', 200]],
    'Pasta, volkoren, gekookt': [OPSCHEP, ['portie', 200]],
    'Pasta, ongekookt': [['portie', 80]],
    'Mie/noedels, gekookt': [OPSCHEP, ['portie', 200]],
    'Couscous, gekookt': [OPSCHEP, ['portie', 150]],
    'Quinoa, gekookt': [OPSCHEP, ['portie', 150]],
    'Aardappelen, gekookt': [['stuk (middel)', 70], OPSCHEP],
    'Aardappelpuree': [OPSCHEP],
    'Friet': [['kleine portie', 100], ['middel portie', 150]],
    'Zoete aardappel, gekookt': [['stuk', 150], OPSCHEP],

    'Kipfilet, gebakken': [['stuk', 120]],
    'Kipfilet, rauw': [['stuk', 150]],
    'Kippendij, gebakken': [['stuk', 90]],
    'Kalkoenfilet, gebakken': [['stuk', 120]],
    'Rundergehakt, gebakken': [['portie', 100], ['gehaktbal', 70]],
    'Gehakt half-om-half, gebakken': [['portie', 100], ['gehaktbal', 70]],
    'Biefstuk, gebakken': [['stuk', 120]],
    'Varkenshaas, gebakken': [['portie', 100]],
    'Rookworst': [['stuk (hele worst)', 275], ['plak', 10]],
    'Kipfilet (vleeswaren)': [PLAK_VLEES],
    'Ham (vleeswaren)': [PLAK_VLEES],
    'Rookvlees': [['plak', 8]],
    'Salami': [['plak', 8]],

    'Zalm, gebakken': [['moot', 125]],
    'Zalm, gerookt': [['plak', 20]],
    'Tonijn in water, uitgelekt': [['blikje (uitgelekt)', 110]],
    'Tonijn in olie, uitgelekt': [['blikje (uitgelekt)', 110]],
    'Kabeljauw, gekookt': [['moot', 125]],
    'Garnalen, gekookt': [EL, ['portie', 100]],
    'Makreel, gerookt': [['portie', 75]],
    'Haring': [['stuk', 70]],
    'Sardines in olie': [['blikje (uitgelekt)', 90], ['stuk', 20]],

    'Tofu': [['portie', 100]],
    'Tempeh': [['portie', 100]],
    'Linzen, gekookt': [OPSCHEP, EL],
    'Kikkererwten, gekookt': [OPSCHEP, EL],
    'Bruine bonen, gekookt': [OPSCHEP, EL],
    'Kidneybonen, gekookt': [OPSCHEP, EL],
    'Edamame': [['portie', 75]],
    'Hummus': [EL, ['voor 1 snee', 15]],
    'Pindakaas': [['voor 1 snee', 15], EL, TL],
    'Pinda\'s': [HAND, EL],
    'Amandelen': [HAND, ['stuk', 1.2]],
    'Walnoten': [HAND, ['stuk (hele noot)', 5]],
    'Cashewnoten': [HAND],
    'Zonnebloempitten': [EL],
    'Chiazaad': [EL, TL],

    'Broccoli, gekookt': [OPSCHEP, ['portie', 200]],
    'Bloemkool, gekookt': [OPSCHEP, ['portie', 200]],
    'Sperziebonen, gekookt': [OPSCHEP, ['portie', 200]],
    'Spinazie, gekookt': [OPSCHEP, ['portie', 200]],
    'Boerenkool, gekookt': [OPSCHEP, ['portie', 200]],
    'Doperwten, gekookt': [OPSCHEP, EL],
    'Wortel': [['stuk', 70], OPSCHEP],
    'Komkommer': [['plak', 7], ['hele komkommer', 350]],
    'Tomaat': [['stuk', 100], ['cherrytomaatje', 12]],
    'Paprika': [['stuk', 150]],
    'Sla': [['handje', 20], ['schaaltje', 50]],
    'Courgette': [['stuk', 250], OPSCHEP],
    'Aubergine': [['stuk', 300], OPSCHEP],
    'Champignons': [['stuk', 15], OPSCHEP],
    'Ui': [['stuk', 100], EL],
    'Prei': [['stuk', 200], OPSCHEP],
    'Knoflook': [['teentje', 4]],
    'Pompoen': [OPSCHEP],
    'Rode biet, gekookt': [['stuk', 100], OPSCHEP],
    'Asperges, gekookt': [['stuk', 20], ['portie', 250]],
    'Maïs (blik)': [EL, ['blikje (uitgelekt)', 140]],
    'Avocado': [['hele avocado', 150], ['halve avocado', 75]],
    'Olijven': [['stuk', 4], EL],

    'Banaan': [['stuk', 120]],
    'Appel': [['stuk', 150]],
    'Peer': [['stuk', 160]],
    'Sinaasappel': [['stuk', 150]],
    'Mandarijn': [['stuk', 60]],
    'Aardbeien': [['stuk', 15], SCHAAL],
    'Blauwe bessen': [HAND, SCHAAL],
    'Frambozen': [HAND, SCHAAL],
    'Kiwi': [['stuk', 75]],
    'Druiven': [['stuk', 5], SCHAAL],
    'Ananas': [['schijf', 80]],
    'Mango': [['stuk', 300], SCHAAL],
    'Meloen': [['part', 150]],
    'Watermeloen': [['part', 250]],
    'Rozijnen': [EL, ['doosje', 14]],
    'Dadels, gedroogd': [['stuk', 8]],

    'Koffie, zwart': [['kop', 125], ['mok', 250]],
    'Thee, zonder suiker': [['kop', 150], ['mok', 250]],
    'Sinaasappelsap': [GLAS],
    'Appelsap': [GLAS],
    'Cola': [GLAS, ['blikje', 330]],
    'Cola zero / light': [GLAS, ['blikje', 330]],
    'Bier (pils)': [['glas', 250], ['flesje', 300], ['blikje', 330]],
    'Wijn, rood': [['glas', 125]],
    'Wijn, wit': [['glas', 125]],
    'Chocolademelk': [GLAS, BEKER],
    'Wheyproteïne (poeder)': [['schep', 30]],

    'Hagelslag, puur': [['voor 1 snee', 15]],
    'Chocoladepasta': [['voor 1 snee', 15], TL],
    'Jam': [['voor 1 snee', 15], TL],
    'Honing': [TL, ['voor 1 snee', 10]],
    'Suiker': [TL, ['klontje', 4], EL],
    'Olijfolie': [EL, TL],
    'Mayonaise': [EL, ['klodder bij friet', 20]],
    'Ketchup': [EL, ['klodder bij friet', 20]],
    'Chocolade, puur': [['blokje', 5], ['reep', 100]],
    'Chocolade, melk': [['blokje', 5], ['reep', 100]],
    'Chips, naturel': [HAND, ['zakje', 40]],
    'Biscuit': [['stuk', 8]],
    'Ontbijtkoek': [['plak', 25]]
  };
})();
